Repository kiitfossosh/personal-websites, pull requests merged in 2020-10, with the labels that each got.

#9 made changes according to the CONTRIBUTE.md
  steganography_DarthCucumber/README.md
  steganography_DarthCucumber/decode.js
  steganography_DarthCucumber/encode.js
  steganography_DarthCucumber/index.html
  steganography_DarthCucumber/tools.js
Labels: hacktoberfest-accepted

#4 Here I Add Basic Projects Using Js and Html and CSS
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Background Colour Change/index.css
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Background Colour Change/index.html
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Background Colour Change/index.js
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Count Number Project/bg2.jpg
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Count Number Project/index.css
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Count Number Project/index.html
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Count Number Project/index.js
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Famous Quotes/bg5.jpg
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Famous Quotes/index.css
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Famous Quotes/index.html
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Famous Quotes/index.js
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Famous Quotes/plan min(project 2).png
Labels: enhancement

#12 django api
  todoRestApi_manav2000/.gitignore
  todoRestApi_manav2000/.vscode/settings.json
  todoRestApi_manav2000/LICENSE
  todoRestApi_manav2000/README.md
  todoRestApi_manav2000/api/__init__.py
  todoRestApi_manav2000/api/admin.py
  todoRestApi_manav2000/api/apps.py
  todoRestApi_manav2000/api/migrations/0001_initial.py
  todoRestApi_manav2000/api/migrations/0002_remove_task_completed.py
  todoRestApi_manav2000/api/migrations/0003_task_completed.py
  todoRestApi_manav2000/api/migrations/__init__.py
  todoRestApi_manav2000/api/models.py
  todoRestApi_manav2000/api/serializers.py
  todoRestApi_manav2000/api/tests.py
  todoRestApi_manav2000/api/urls.py
  todoRestApi_manav2000/api/views.py
  todoRestApi_manav2000/frontend/__init__.py
  todoRestApi_manav2000/frontend/admin.py
  todoRestApi_manav2000/frontend/apps.py
  todoRestApi_manav2000/frontend/migrations/__init__.py
  todoRestApi_manav2000/frontend/models.py
  todoRestApi_manav2000/frontend/tests.py
  todoRestApi_manav2000/frontend/urls.py
  todoRestApi_manav2000/frontend/views.py
  todoRestApi_manav2000/manage.py
  todoRestApi_manav2000/requirements.txt
  todoRestApi_manav2000/rest_api/__init__.py
  todoRestApi_manav2000/rest_api/asgi.py
  todoRestApi_manav2000/rest_api/settings.py
  todoRestApi_manav2000/rest_api/urls.py
  todoRestApi_manav2000/rest_api/wsgi.py
  todoRestApi_manav2000/static/css/style.css
  todoRestApi_manav2000/static/js/main.js
  todoRestApi_manav2000/templates/frontend/todo_list.html
Labels: enhancement, hacktoberfest-accepted

#13 Update index.css
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Background Colour Change/index.css
Labels: enhancement, hacktober-accepted

#15 A smart assistant made using python
  WALL-E_Praddy2009/Index.html
  WALL-E_Praddy2009/README.md
  WALL-E_Praddy2009/css/style.css
  WALL-E_Praddy2009/images/Img.jpg
  WALL-E_Praddy2009/images/robo.jpg
  WALL-E_Praddy2009/images/robo1.jpg
  WALL-E_Praddy2009/linux.py
Labels: enhancement, hacktoberfest-accepted

#14 Updated the index.html file
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Count Number Project/index.html
Labels: enhancement, hacktoberfest-accepted

#17 Update index.css file
  3 _Beginner_Level_Project_in_Js_Faizan-Alam-1/Background Colour Change/index.css
Labels: enhancement, hacktoberfest-accepted

#20 Adding my beginner projects folder
  BeginnerProjects_joypatel9/Exchange Rate Calculator/.vscode/settings.json
  BeginnerProjects_joypatel9/Exchange Rate Calculator/README.md
  BeginnerProjects_joypatel9/Exchange Rate Calculator/img/money.png
  BeginnerProjects_joypatel9/Exchange Rate Calculator/index.html
  BeginnerProjects_joypatel9/Exchange Rate Calculator/script.js
  BeginnerProjects_joypatel9/Exchange Rate Calculator/style.css
Labels: hacktoberfest-accepted

#19 url-shortner using NodeJS
  url-shortner_dibyendu415/README.md
  url-shortner_dibyendu415/models/shorturl.js
  url-shortner_dibyendu415/package-lock.json
  url-shortner_dibyendu415/package.json
  url-shortner_dibyendu415/server.js
  url-shortner_dibyendu415/views/index.ejs
Labels: hacktoberfest-accepted

#21 Adding another small project to my folder
  BeginnerProjects_joypatel9/Breathing Relaxer App/README.md
  BeginnerProjects_joypatel9/Breathing Relaxer App/img/bg.jpg
  BeginnerProjects_joypatel9/Breathing Relaxer App/index.html
  BeginnerProjects_joypatel9/Breathing Relaxer App/script.js
  BeginnerProjects_joypatel9/Breathing Relaxer App/style.css
Labels: hacktoberfest-accepted

#22 Adding New Year Countdown project
  BeginnerProjects_joypatel9/Movie Seat Booking/README.md
  BeginnerProjects_joypatel9/Movie Seat Booking/index.html
  BeginnerProjects_joypatel9/Movie Seat Booking/script.js
  BeginnerProjects_joypatel9/Movie Seat Booking/style.css
  BeginnerProjects_joypatel9/New Year Countdown/README.md
  BeginnerProjects_joypatel9/New Year Countdown/img/spinner.gif
  BeginnerProjects_joypatel9/New Year Countdown/index.html
  BeginnerProjects_joypatel9/New Year Countdown/script.js
  BeginnerProjects_joypatel9/New Year Countdown/style.css
Labels: hacktoberfest-accepted

#24 A Dog-Dating Site made using Bootstrap Framework
  Tindog_spandan1460/css/styles.css
  Tindog_spandan1460/images/TechCrunch.png
  Tindog_spandan1460/images/bizinsider.png
  Tindog_spandan1460/images/dog-img.jpg
  Tindog_spandan1460/images/iphone6.png
  Tindog_spandan1460/images/lady-img.jpg
  Tindog_spandan1460/images/mashable.png
  Tindog_spandan1460/images/tnw.png
  Tindog_spandan1460/index.html
Labels: hacktoberfest-accepted
